<?php
namespace App\Utils;
use Symfony\Component\HttpFoundation\Request as SymfonyRequest;

class Request extends SymfonyRequest
{
	public function __construct(array $query = array(), array $request = array(), array $attributes = array(), array $cookies = array(), array $files = array(), array $server = array(), $content = null){
		parent::__construct($query,$request,$attributes ,$cookies,$files,$server,$content);
	}
	/**
	 * @param bool $asResource
	 * @return string
	 */
	public function getContent($asResource = false)
	{
//		parent::getContent($asResource); // TODO: Change the autogenerated stub
//		if (null == $this->content || false === $this->content) {
			$this->content = \ezswoole\Request::getInstance()->getEsRequest()->getSwooleRequest()->rawContent();
//		}
		return $this->content;
	}

	public static function clearRequestFactory(){
		self::$requestFactory = null;
	}

}